### ISSUE TITLE
I want to know what the data is 

### ISSUE THREAD

**Issue by O2Dyokii** [barkain/DeepAndCrossNetwork#1]
Hi, Can you tell me what the data is? Thanks

**Comment by barkain** [comment]
Hi, the model is implemented using proprietary real-time bidding data.
Essentially, these are requests obtained by connecting to RTB platform.
The data consists of several types of features - categorical, binary and cyclic (numeric).

**Comment by O2Dyokii** [comment]
Ok, Thank you
